apiVersion: apps/v1
kind: Deployment
metadata:
 name: config-service
 labels:
   app: config-service
spec:
 replicas: 1
 selector:
   matchLabels:
     app: config-service
 template:
   metadata:
     labels:
       app: config-service
   spec:
     containers:
       - name: config-service
         # ECR 이미지 주소로 수정
         image: 730335665695.dkr.ecr.ap-northeast-2.amazonaws.com/config-service:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 8888
         resources:
           requests:
             cpu: "250m"
             memory: "512Mi"
           limits:
             cpu: "500m"
             memory: "1Gi"
         readinessProbe:
           httpGet:
             path: /actuator/health
             port: 8888
           initialDelaySeconds: 30
           periodSeconds: 10
         livenessProbe:
           httpGet:
             path: /actuator/health
             port: 8888
           initialDelaySeconds: 40
           periodSeconds: 20